### ISSUE TITLE
Callback URL

### ISSUE THREAD

**Issue by garybrowne** [alexandermendes/pybossa-github-builder#2]
Hi Alex,
I've installed this plugin in my pybossa installation and created a github application - but I can't work out what to use as the authorization callback URL. Any help you could offer would be much appreciated, as I still don't have a "Sync with GitHub" option on my dashboard in PyBossa (ultimately I'm trying to get project-convert-a-card working).
Thanks,
Gary

**Comment by alexandermendes** [comment]
Hi Gary,

So, the callback URL would be `https://{your-pybossa-domain}/github/oauth-authorized` and to get the "Sync with GitHub" link you need to add something like this wherever you want the link to appear:

``` HTML+Django
{% if 'pybossa_github_builder' in plugins %}
    <a href="{{ url_for('github.sync', short_name=project.short_name) }}">Sync with GitHub</a>
{% endif %}
```

Note that you will also need the [pybossa-z3950](https://github.com/alexandermendes/pybossa-z3950) plugin to get the convert-a-card projects working. I'll try to update the docs soon to make this a bit clearer.
